morning-night-guild/platform

.github/workflows/api.document.yml, README.md
@Shitomo 
- [api](https://github.com/morning-night-guild/platform/tree/gh-pages/api)
- [database](https://github.com/morning-night-guild/platform/tree/gh-pages/database)
こんな感じに出力されます。
=> #5 ドキュメントを自動生成するCIを追加

.github/workflows/api.lint.yml, api/Makefile, api/article/v1/article.proto
@Shitomo 
CIにて`proto`ファイルの静的解析を行えるようにしました。
=> #9 CIにてprotoファイルの静的解析を実施

.github/workflows/container.push.yml, backend/app/core/.ko.yml, backend/app/core/cloudbuild.yaml, container/builder/Dockerfile, container/deployer/Dockerfile
記事共有サービスのデプロイの設定を追加しました。  
mainブランチのマージにより発火するように設定してあります。
=> #6 記事共有サービスの自動デプロイを設定

backend/app/core/adapter/controller/error.go, backend/app/core/adapter/gateway/ogp.go, backend/app/core/model/errors/url_error.go
@Shitomo 
ogp作成時に200以外の場合はエラーが発生するように修正しました。
=> #61 ステータスコードが200以外ではogpは作成しないように修正

backend/aqua.yaml
@Shitomo 
golangci-lintのバージョンを更新しました。
=> #21 golangci-lintのバージョンを更新

.github/workflows/backend.vulnerability.yml
@Shitomo 
CIにてコンテナの脆弱性を診断するように設定しました。
https://github.com/morning-night-guild/platform/actions/runs/3303854342
実行結果です。
=> #75 CIにてコンテナの脆弱性を診断するように設定

.github/actions/frontend/setup/action.yml, .github/workflows/frontend.lint.yml
@Shitomo 
frontendの静的解析ジョブを設定しました。
実行結果
https://github.com/morning-night-guild/platform/actions/runs/3307270620/jobs/5458776385
=> #83 frontendの静的解析をCIにて実行するように設定

.github/workflows/infra.image.clean.yml
=> #107 日次で不要なコンテナを削除するバッチを実装

.github/workflows/infra.image.clean.yml
@takokun778 
オーディエンスが前のリポジトリのままでバッチがこけていたので修正
=> #107 オーディエンス名を修正

renovate.json
@Shitomo 
aqua も renovate 対象となるように設定しました。
=> #129 aquaもrenovate対象となるように設定

renovate.json
- フロントエンドは、メジャーアップデート以外は同じPRにまとめるよう修正
- TypeScriptの型定義のアップデートは一つのPRにまとめるよう修正
を実施しました
=> #153 フロントエンドについて、renovateのPRの頻度を調整

README.md
@Shitomo 
ディレクトリ構成が変更になったので説明を追記しました。
=> #168 README.mdのディレクトリ構成の説明を修正

.github/workflows/supabase.deploy.yml, .github/workflows/supabase.test.yml, supabase/.vscode/settings.json, supabase/Makefile, supabase/README.md, supabase/functions/slack/index.test.ts, supabase/functions/slack/index.ts
supabase/functionsディレクトリ以下の、サブディレクトリ内含む全てのtsファイルへの変更に対してジョブが走るようにしました
=> #181 supabaseのジョブの発火条件を調整

.github/workflows/backend.container.push.yml, .github/workflows/backend.diff.yml
=> #193 go,modとgo.sumに変更があった場合にCIが実行されるように設定

backend/go.mod
@Shitomo 
go.mod を整頓しました。
何がきっかけで `require` ブロックが分かれたのかは言及できていないです。
=> #228 go.modを整頓

.github/workflows/backend.container.push.yaml
@Shitomo 
tag名を書き換える処理を修正しました。
https://github.com/morning-night-guild/platform-manifest/pull/22
先にこちらのマージが必要です。
=> #238 tag名を書き換える処理を修正

.github/workflows/backend.container.push.yaml
=> #238 CIのタグ指定を修正

.github/workflows/backend.e2e.yaml, backend/.gitignore, backend/Makefile, backend/README.md, backend/e2e/article/client.go, backend/e2e/article/share_test.go, backend/e2e/health/check_test.go, backend/e2e/health/client.go, backend/e2e/helper/api_key.go, backend/e2e/helper/endpoint.go, backend/e2e/helper/transport.go
@Shitomo 
e2eテストを実装しCIでも実行するようにしました。
=> #251 e2eテストを追加

.docker/docker-compose.yaml, .github/workflows/backend.container.push.yaml, .github/workflows/backend.test.e2e.yaml, backend/cmd/core/main.go, backend/internal/driver/config/config.go, backend/internal/driver/config/config_test.go, backend/internal/driver/server/cors.go, backend/internal/driver/server/cors_test.go, backend/internal/driver/server/server.go, backend/pkg/log/log.go, frontend/package.json
マニフェストの修正: https://github.com/morning-night-guild/platform-infra/pull/20
=> #295 connect-goの仕様に合わせてCORSの設定を修正

frontend/src/swr/useApiArticle.ts
maxPageSizeプロパティとして指定してあげる必要がありました 💦
でないとサーバー側のバリデーションで弾かれる...
=> #302 articlesPerPageをmaxPageSizeプロパティとして指定するよう修正

.github/workflows/backend.deploy.yaml, .github/workflows/document.yaml
@Shitomo 
manifest更新方法を修正しました。
関連PR
https://github.com/morning-night-guild/platform-infra/pull/35
=> #327 manifest更新方法を修正

.github/workflows/backend.test.e2e.yaml, .github/workflows/backend.vulnerability.yaml, backend/.gitignore, backend/Makefile, backend/e2e/appapi/article/list_test.go, backend/e2e/appapi/article/share_test.go, backend/e2e/appapi/health/check_test.go, backend/e2e/appcore/article/list_test.go, backend/e2e/appcore/article/share_test.go, backend/e2e/appcore/health/check_test.go
=> #343 不要なビルドタグを削除
